name: adopt_uas
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  shared_preferences: ^2.0.15
  http: ^1.2.1
  image_picker: ^0.8.6
  image: ^3.2.2
  path_provider: ^2.0.11

flutter:
  uses-material-design: true
